version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["sleep", "infinity"]
    stdin_open: true
    tty: true
    init: true

  frontend:
    image: node:18
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace
    # command: sh -c "npm install && npm run dev"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: order_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
